{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent-smith.fullname" . }}
  labels:
    {{- include "agent-smith.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.rbac.rules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent-smith.fullname" . }}
  labels:
    {{- include "agent-smith.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent-smith.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent-smith.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
