{{/* TODO Task 4: rewrite for agents array */}}
{{- if false }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-smith.serviceAccountName" . }}
  labels:
    {{- include "agent-smith.labels" . | nindent 4 }}
{{- end -}}
{{- end }}
