{{- if .Values.serviceAccount.create }}
{{- $root := . -}}
{{- $agents := fromJsonArray (include "agent-smith.agentList" .) -}}
{{- range $agent := $agents }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $agent.name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "agent-smith.labels" $root | nindent 4 }}
    agent-smith.io/agent: {{ $agent.name }}
{{- end }}
{{- end }}
